source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ATRLogFormatterDemo', :exclusive => true do
  pod "ATRLogFormatter", :path => "../"
end

target 'ATRLogFormatterDemoTests', :exclusive => true do
  pod "ATRLogFormatter", :path => "../"


end
